//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDAKyThuatSource.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CumThietBi
    {
        public CumThietBi()
        {
            this.KeHoach = new HashSet<KeHoach>();
            this.LichSu = new HashSet<LichSu>();
            this.ThongSoKT = new HashSet<ThongSoKT>();
        }
    
        public int iMaCum { get; set; }
        public string sTenCum { get; set; }
        public Nullable<int> iMaThietBi { get; set; }
    
        public virtual ThietBi ThietBi { get; set; }
        public virtual ICollection<KeHoach> KeHoach { get; set; }
        public virtual ICollection<LichSu> LichSu { get; set; }
        public virtual ICollection<ThongSoKT> ThongSoKT { get; set; }
    }
}
