//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDAKyThuatSource.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonVi
    {
        public DonVi()
        {
            this.Chuyen = new HashSet<Chuyen>();
            this.NhanVien = new HashSet<NhanVien>();
        }
    
        public int iMaDonVi { get; set; }
        public string sTenDonVi { get; set; }
        public string sDiaChi { get; set; }
    
        public virtual ICollection<Chuyen> Chuyen { get; set; }
        public virtual ICollection<NhanVien> NhanVien { get; set; }
    }
}
