//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDAKyThuatSource.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LichSu
    {
        public int iMaLS { get; set; }
        public Nullable<System.DateTime> dNgay { get; set; }
        public string sNoiDung { get; set; }
        public string sCachKhacPhuc { get; set; }
        public string sGhiChu { get; set; }
        public Nullable<bool> bSuCo { get; set; }
        public Nullable<int> iMaCum { get; set; }
    
        public virtual CumThietBi CumThietBi { get; set; }
    }
}
