//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDAKyThuatSource.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhanVien
    {
        public int iMaNV { get; set; }
        public string sTenNV { get; set; }
        public string sTaiKhoan { get; set; }
        public string sMatKhau { get; set; }
        public string sEmail { get; set; }
        public string sChucVu { get; set; }
        public string sPhongBan { get; set; }
        public Nullable<int> iMaDonVi { get; set; }
    
        public virtual DonVi DonVi { get; set; }
    }
}
