//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDAKyThuatSource.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TDAKTEntities : DbContext
    {
        public TDAKTEntities()
            : base("name=TDAKTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CumThietBi> CumThietBi { get; set; }
        public virtual DbSet<Chuyen> Chuyen { get; set; }
        public virtual DbSet<DonVi> DonVi { get; set; }
        public virtual DbSet<Hinh> Hinh { get; set; }
        public virtual DbSet<KeHoach> KeHoach { get; set; }
        public virtual DbSet<LichSu> LichSu { get; set; }
        public virtual DbSet<NhanVien> NhanVien { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<ThietBi> ThietBi { get; set; }
        public virtual DbSet<ThongSoKT> ThongSoKT { get; set; }
    }
}
