//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDAKyThuatSource.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongSoKT
    {
        public ThongSoKT()
        {
            this.Hinh = new HashSet<Hinh>();
        }
    
        public int iMaTSKT { get; set; }
        public string sThongSoKT { get; set; }
        public string sDVT { get; set; }
        public Nullable<int> iSoLuong { get; set; }
        public Nullable<int> iTTNCC { get; set; }
        public Nullable<int> iTTTT { get; set; }
        public Nullable<int> iTTDT { get; set; }
        public Nullable<int> iTTCL { get; set; }
        public string sHinh { get; set; }
        public Nullable<int> iMaCum { get; set; }
    
        public virtual CumThietBi CumThietBi { get; set; }
        public virtual ICollection<Hinh> Hinh { get; set; }
    }
}
